[project]
name = "speedtest-to-influxdb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "influxdb-client[ciso]>=1.49.0",
    "schedule>=1.2.2",
]

[dependency-groups]
dev = []
