# compose.yaml
services:
  influxdb2:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: db_username
      DOCKER_INFLUXDB_INIT_PASSWORD: db_password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: MyTestAdminToken0==
      DOCKER_INFLUXDB_INIT_ORG: default
      DOCKER_INFLUXDB_INIT_BUCKET: default
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
      start_interval: 5s
  speedtesttoinfluxdb:
    build: .
    environment:
      DB_ADDRESS: influxdb2
      RUN_ONCE: True
    depends_on: 
      influxdb2:
        condition: service_healthy
volumes:
  influxdb2-data:
  influxdb2-config: