{
 "title": "Speedtest",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "type": "canvas", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    { "expression": "$A / 125000", "type": "math" }
   ]
  },
  {
   "title": "Upload Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    { "expression": "$A / 125000", "type": "math" }
   ]
  },
  {
   "title": "Download Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Latency (High mean)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "download",
     "select": [
      [
       { "params": [ "latency_high" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Latency (Low mean)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "download",
     "select": [
      [
       { "params": [ "latency_low" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Packet Loss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "packetLoss",
     "select": [
      [
       { "params": [ "packetLoss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Packet Loss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Latency (High mean)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upload",
     "select": [
      [
       { "params": [ "latency_high" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Latency (Low mean)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upload",
     "select": [
      [
       { "params": [ "latency_low" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}