name: Build and Push Docker Image on Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: docker

    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase repository name
      run: |
        echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Extract release version
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ env.REPO_LC }}
        tags: |
          type=sha
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ghcr.io/${{ env.REPO_LC }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true